# Generated by Django 2.1.1 on 2018-09-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackingservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='token_no',
            field=models.IntegerField(default=5257),
        ),
        migrations.AlterField(
            model_name='user',
            name='token_no',
            field=models.IntegerField(default=6748),
        ),
    ]
