# Generated by Django 2.1.1 on 2018-09-08 11:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trackingservice', '0002_auto_20180908_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientService',
            fields=[
                ('service_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('contact_no', models.CharField(max_length=10, unique=True)),
                ('address', models.TextField()),
                ('token_no', models.IntegerField(default=5504)),
                ('profile_pic', models.ImageField(upload_to='user/profile/pic')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DriverService',
            fields=[
                ('service_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_lat', models.FloatField()),
                ('start_long', models.FloatField()),
                ('stop_lat', models.FloatField(null=True)),
                ('stop_long', models.FloatField()),
                ('bus_no', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackingservice.Driver')),
            ],
        ),
        migrations.CreateModel(
            name='DriverStatus',
            fields=[
                ('status_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackingservice.DriverService')),
            ],
        ),
        migrations.CreateModel(
            name='UserService',
            fields=[
                ('service_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='token_no',
            field=models.IntegerField(default=3409),
        ),
        migrations.AlterField(
            model_name='user',
            name='token_no',
            field=models.IntegerField(default=5636),
        ),
        migrations.AddField(
            model_name='userservice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackingservice.User'),
        ),
        migrations.AddField(
            model_name='clientservice',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackingservice.Driver'),
        ),
        migrations.AddField(
            model_name='clientservice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackingservice.User'),
        ),
    ]
